version: "3.8"

services:
    app:
      build: .
      volumes: 
        - .:/django_demo/django_demo
      ports:
        - 8000:8000
      image: app:project
      container_name : container
      command: python3 manage.py runserver 0.0.0.0:8000
   